spring:
  application:
    name: ai-rag

  config:
    activate:
      on-profile: postgres
  datasource:
    username: postgresml
    #password: password
    url: jdbc:postgresql://localhost:5433/postgresml
  ai:
    postgresml:
      embedding:
        options:
          transformer: distilbert-base-uncased
          vectorType: PG_ARRAY
          metadataMode: EMBED
          kwargs:
            device: cpu
#    ollama:
#      embedding:
#        options:
#          model: chroma/all-minilm-l6-v2-f32
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        schema-name: public
        table-name: vector_store
#      milvus:
#        client:
#          host: "localhost"
#          port: 19530
#          username: "root"
#          password: "milvus"
#        databaseName: "atom"
#        collectionName: "atom_vector5"
#        embeddingDimension: 1536
#        indexType: IVF_FLAT
#        metricType: COSINE
#  ai:
#    openai:
#      api-key: ${OPENAI_API_KEY}
ai-search:
  ai-app:
    documentsToLoad:
      - classpath:/movie2.csv
---

spring:
  config:
    activate:
      on-profile: simple
#  ai:
#    ollama:
#      embedding:
#        options:
#          model: chroma/all-minilm-l6-v2-f32

#  ai:
#    openai:
#      api-key: ${OPENAI_API_KEY}
ai-search:
  ai-app:
    vectorStorePath: /Users/ravisingh/mlearning/search/tmp/vectorstore.json
    documentsToLoad:
      - classpath:/movie2.csv